language: csharp
solution: Ticketmaster-SDK.sln
dist: trusty
mono: none
install:
- dotnet restore
script:
- dotnet build
- dotnet test Ticketmaster.Discovery.Tests/Ticketmaster.Discovery.Tests.csproj
