language: csharp
solution: ./src/TM-SDK/Ticketmaster-SDK.sln
install:
  - nuget restore ./src/TM-SDK/Ticketmaster-SDK.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.6.1 ./src/TM-SDK/Ticketmaster-SDK.sln"
